### ISSUE TITLE
Same comment on each page

### ISSUE THREAD

**Issue by benjamingeorge** [theplatapi/react-disqus-thread#16]
I'm using this component on an app with may "posts" .  On each page I'm passing a unique identifier and url that matches the post slug which is indeed unique.  However I see the same comments for each post even when I add a key prop to force a remount of the post component.   Also looking in the Network tab it is indeed making different requests to discus, yet the same comments are returned.  Anyone else come across this issue ?

**Comment by LucasWG94** [comment]
I have the same problem
Did you find a solution?

**Comment by sir-pinecone** [comment]
@benjamingeorge I'm experiencing the same thing. My disqus moderation page is showing me odd original page URLs for some comments too, like `<sitename>.comundefined/#comment-<id>`

Did you happen to find a fix for this?

EDIT: I realized the issue was on my end. Due to some config changes, the Disqus identifier was being shared by multiple posts. Maybe check to see if you're sharing ids.
